### ISSUE TITLE
CollectionRoot hash check should be inside of bolt tx

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1447]
In this code:
```
	log.Lvlf3("%s: Storing %d state changes %v", s.ServerIdentity(), len(scs), scs.ShortStrings())
	if err = cdb.StoreAll(scs); err != nil {
		return err
	}
	if !bytes.Equal(cdb.RootHash(), data.CollectionRoot) {
		log.Error("hash of collection doesn't correspond to root hash")
	}
```
by the time that the collection root is detected as out of sync, both the on-disk and the in-memory collections are already compromised by the bad state changes in the block.

The comparison of the collection root should happen inside the boltdb transaction, so that on failure the tx can ben aborted without being applied. That would still leave the in-memory copy corrupt, so the server should exit at that point via os.Exit (not panic, because that could be caught).

**Comment by ineiti** [comment]
Should be fixed by the new collection.

**Comment by kc1212** [comment]
Actually this issue still exists. I propose we create a new method like `VerifiedStoreAll(scs, sb.Index, rootHash)` and put the verification check inside the transaction.
