### ISSUE TITLE
Double-closing of done-channel

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#750]
```
panic: close of closed channel
goroutine 11766 [running]:
panic(0x8087e0, 0xc4203f2700)
        /usr/lib/golang/src/runtime/panic.go:500 +0x1a1
github.com/dedis/cothority/cosi/protocol.(*CoSi).handleResponse.func1(0xc4229cd040)
        /home/isma/gocode/src/github.com/dedis/cothority/cosi/protocol/cosi.go:267 +0x2f
github.com/dedis/cothority/cosi/protocol.(*CoSi).handleResponse(0xc4229cd040, 0xc422a83dd0, 0xa75060, 0xc4203f26f0)
        /home/isma/gocode/src/github.com/dedis/cothority/cosi/protocol/cosi.go:274 +0x3d6
github.com/dedis/cothority/cosi/protocol.(*CoSi).Dispatch(0xc4229cd040, 0x0, 0x0)
        /home/isma/gocode/src/github.com/dedis/cothority/cosi/protocol/cosi.go:140 +0x4cf
created by github.com/dedis/cothority/cosi/service.(*CoSi).NewProtocol
        /home/isma/gocode/src/github.com/dedis/cothority/cosi/service/cosi.go:88 +0xf4
```

Cause: `handleResponse` will be called once for each child, but it should close the channel only once all children replied.

**Comment by ineiti** [comment]
Added some debugging-outputs to understand what's going on.

**Comment by Liamsi** [comment]
It panicked again after restarting with the same error. I did what you told me and I get a 
```
$ cd $GOPATH/src/github.com/dedis/cothority
$ git pull
$ git checkout cosi_double_750
Branch cosi_double_750 set up to track remote branch cosi_double_750 from origin.
Switched to a new branch 'cosi_double_750'
$ go get -u ./...
package github.com/dedis/onet/app/config: cannot find package "github.com/dedis/onet/app/config" in any of:
        /usr/lib/golang/src/github.com/dedis/onet/app/config (from $GOROOT)
        /home/isma/gocode/src/github.com/dedis/onet/app/config (from $GOPATH)
package github.com/dedis/onet/app/server: cannot find package "github.com/dedis/onet/app/server" in any of:
        /usr/lib/golang/src/github.com/dedis/onet/app/server (from $GOROOT)
        /home/isma/gocode/src/github.com/dedis/onet/app/server (from $GOPATH)
```
dedis/onet is the most recent version of master in my side. Does it require a specific version, too?

**Comment by Liamsi** [comment]
Seems like you have some local (not pushed) branch of `onet` running together with `cosi_double_750`. I switched back to master for all repos for now.

**Comment by ineiti** [comment]
Oups - forgot to merge with master. Should work now.

**Comment by Liamsi** [comment]
On `cosi_double_750` I still get the same error message (as in https://github.com/dedis/cothority/issues/750#issuecomment-271083167).

**Comment by Liamsi** [comment]
There seem to have  been more changes in the meantime: ran a week without panic'ing 👍  Closing this one. (I'm updating to v1 right now, by the way).
